version: '3.8'

services:
  frontend:
    image: frontend:prod-v1.0.1
    networks:
      - smartzap_net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  backend:
    image: backend:prod-v1.0.1
    networks:
      - smartzap_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  smartzap_net:
    driver: overlay
    attachable: true
