version: '3.8'

services:
  frontend:
    image: smartzap-frontend:latest
    networks:
      - smartzap_net
    ports:
      - "8080:80"
      - "8443:443"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    volumes:
      - ./frontEnd/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs

  backend:
    image: smartzap-backend:latest
    networks:
      - smartzap_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    environment:
      - NODE_ENV=production

networks:
  smartzap_net:
    driver: overlay
    attachable: true
