version: '3.8'

services:
  frontend:
    image: smartzap-frontend:latest
    container_name: frontend_container
    networks:
      - smartzap_net
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./frontEnd/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs

  backend:
    image: smartzap-backend:latest
    container_name: backend_container
    networks:
      - smartzap_net
    expose:
      - "4000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - NODE_ENV=production

networks:
  smartzap_net:
    driver: overlay
    attachable: true
