version: '3.8'

services:
  frontend:
    image: frontend:prod-v1.0.1
    container_name: frontend_container
    networks:
      - smartzap_net
    ports:
      - "80:80"       # Mapeia a porta 80 do contêiner para a porta 80 do host
      - "443:443"     # Mapeia a porta 443 do contêiner para a porta 443 do host
    depends_on:
      - backend       # Garante que o backend seja iniciado antes do frontend
    #volumes:
    #  - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mapeia o nginx.conf do host para o contêiner
    #  - ./certs:/etc/nginx/certs                      # Mapeia os certificados SSL, se necessário

  backend:
    image: backend:prod-v1.0.1
    container_name: backend_container
    networks:
      - smartzap_net
    #environment:
    #  - DATABASE_URL=mysql://user:password@db:3306/dbname  # Exemplo de variáveis de ambiente (ajuste conforme necessário)
    expose:
      - "4000"       # Expõe a porta 4000 apenas para outros serviços no Docker (não para o host)
    #volumes:
    #  - ./data:/var/lib/backend/data  # Exemplo de volume para dados persistentes (ajuste conforme necessário)

networks:
  smartzap_net:
    driver: bridge
